const HOMEPAGE_DEFAULT_IMAGE_URL = '/images-next/default-og-img.png'
const HOMEPAGE_LATEST_NEWS_FILE_COUNT = 4
const HOMEPAGE_LATEST_NEWS_COUNT = 8
const HOMEPAGE_MORE_NEWS_BATCH_SIZE = 30

export {
  HOMEPAGE_DEFAULT_IMAGE_URL,
  HOMEPAGE_LATEST_NEWS_COUNT,
  HOMEPAGE_LATEST_NEWS_FILE_COUNT,
  HOMEPAGE_MORE_NEWS_BATCH_SIZE,
}
