const HOMEPAGE_DEFAULT_IMAGE_URL = '/images-next/default-og-img.png'
// Must match Tailwind's xl breakpoint for homepage layout behavior.
const HOMEPAGE_DESKTOP_MEDIA_QUERY = '(min-width: 1280px)'
const HOMEPAGE_LATEST_NEWS_FILE_COUNT = 4
const HOMEPAGE_LATEST_NEWS_COUNT = 8
const HOMEPAGE_MORE_NEWS_BATCH_SIZE = 30

export {
  HOMEPAGE_DEFAULT_IMAGE_URL,
  HOMEPAGE_DESKTOP_MEDIA_QUERY,
  HOMEPAGE_LATEST_NEWS_COUNT,
  HOMEPAGE_LATEST_NEWS_FILE_COUNT,
  HOMEPAGE_MORE_NEWS_BATCH_SIZE,
}
